export const themeColors = {
  light: {
    primary: '#a77d35',
    primaryForeground: '#fafaf9',
    background: '#f6f2e9',
    foreground: '#0c0a09',
    mutedForeground: '#78716c',
    card: '#ffffff',
    border: '#e7e4de',
    input: '#e7e4de',
    secondary: '#f5f5f0',
    secondaryForeground: '#1c1917',
    destructive: '#ef4444',
    destructiveForeground: '#fafaf9',
    warning: '#f59e0b',
    warningForeground: '#0c0a09',
    success: '#16a34a',
    successForeground: '#fafaf9',
    // Soft badge backgrounds
    successSoft: '#dcfce7',
    warningSoft: '#fef3c7',
    destructiveSoft: '#fee2e2',
    primarySoft: '#fdf0dc',
  },
  dark: {
    primary: '#a77d35',
    primaryForeground: '#fafaf9',
    background: '#0c0a09',
    foreground: '#fafaf9',
    mutedForeground: '#a8a29e',
    card: '#1c1917',
    border: '#292524',
    input: '#292524',
    secondary: '#262120',
    secondaryForeground: '#fafaf9',
    destructive: '#ef4444',
    destructiveForeground: '#fafaf9',
    warning: '#f59e0b',
    warningForeground: '#0c0a09',
    success: '#22c55e',
    successForeground: '#fafaf9',
    // Soft badge backgrounds (muted for dark)
    successSoft: '#14532d',
    warningSoft: '#451a03',
    destructiveSoft: '#450a0a',
    primarySoft: '#422006',
  },
  amoled: {
    primary: '#a77d35',
    primaryForeground: '#fafaf9',
    background: '#000000',
    foreground: '#fafaf9',
    mutedForeground: '#a8a29e',
    card: '#080808',
    border: '#1a1a1a',
    input: '#1a1a1a',
    secondary: '#0d0d0d',
    secondaryForeground: '#fafaf9',
    destructive: '#ef4444',
    destructiveForeground: '#fafaf9',
    warning: '#f59e0b',
    warningForeground: '#0c0a09',
    success: '#22c55e',
    successForeground: '#fafaf9',
    // Soft badge backgrounds (very dark for AMOLED)
    successSoft: '#0a2a15',
    warningSoft: '#1a0f00',
    destructiveSoft: '#1a0505',
    primarySoft: '#1a1000',
  },
};

export type ThemeColors = typeof themeColors.light;
export type ThemeKey = keyof typeof themeColors;
